
server:
  port: 7575

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/UniFinalDB
    username: postgres
    password: asd123asd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
